### PR TITLE
Support text_mode from signal-cli-rest-api

### PR DESCRIPTION
**Pull request by braveheuel**
* The text_mode can be "normal" or "styled".
* With "styled" mode italic, bold and strikethough text can be send.
* To be backward compatible the default mode is set to "normal".

### CODE REVIEW

**Comment by braveheuel** [comment]
This PR closes #15

**Comment by r-xyz** [comment]
Hello Christoph,
thank you for the great library and related integrations.
I saw this PR and I was wondering if there was a reason why its merge is on-hold.
It would be a great improvement for notifications. :)

**Comment by braveheuel** [comment]
Hi r-xyz! I think, you wanted to address Bernhard (@bbernhard) for his great library and related integrations! I can only repeat what you were saying!

**Comment by r-xyz** [comment]
Hi again,
Apologies, I need some extra coffee today! :facepalm:  
Yes, I meant thanks to Berhhard for the library and to you for this addition!
If any help might be needed for having it merged, I would be happy to help.

**Pull request merged**
